---
- name: Remove from multiple namespaces
  hosts: localhost
  vars:
    namespaces:
      - dev1
      - test1
      - prod1
    container_name: nginx  

  tasks:
    - name: Delete Service in each namespace
      kubernetes.core.k8s:
        state: absent
        kind: Service
        name: "{{ container_name }}"
        namespace: "{{ item }}"
      loop: "{{ namespaces }}"

    - name: Delete Deployment in each namespace
      kubernetes.core.k8s:
        state: absent
        kind: Deployment
        name: "{{ container_name }}"
        namespace: "{{ item }}"
      loop: "{{ namespaces }}"

    - name: Delete namespaces if they are empty
      kubernetes.core.k8s:
        state: absent
        kind: Namespace
        name: "{{ item }}"
      loop: "{{ namespaces }}"
